export const PROPERTIES = [
  {
    id: 1, slug: 'apt-ramallah-masyon',
    title: 'شقة فاخرة — رام الله الجديدة',
    titleEn: 'Luxury Apartment — New Ramallah',
    location: 'رام الله، حي المصيون',
    city: 'رام الله', neighborhood: 'المصيون',
    price: 850000, type: 'sale',
    category: 'apt', tag: 'مميز',
    rooms: 4, baths: 2, area: 180, floor: 3, year: 2021, parking: 1,
    emoji: '🏙️',
    gradient: 'linear-gradient(135deg,#1a3a5c,#0D2B45)',
    images: ['🏙️','🛋️','🚿','🌃'],
    features: ['تكييف مركزي','مصعد','موقف','أمن 24 ساعة','إنترنت فايبر','مدخل خاص'],
    description: 'شقة فاخرة في قلب رام الله الجديدة، تشطيب راقٍ بالكامل، تطل على المدينة. تتضمن مطبخاً مجهزاً، غرفة خادمة، وتراساً خاصاً.',
    agentId: 1,
    views: 234, favorites: 18,
    lat: 31.9038, lng: 35.2034,
    verified: true, featured: true,
  },
  {
    id: 2, slug: 'villa-nablus-rafidya',
    title: 'فيلا عائلية — نابلس',
    titleEn: 'Family Villa — Nablus',
    location: 'نابلس، رفيديا',
    city: 'نابلس', neighborhood: 'رفيديا',
    price: 1200000, type: 'sale',
    category: 'villa', tag: 'فيلا',
    rooms: 6, baths: 3, area: 350, floor: 1, year: 2019, parking: 2,
    emoji: '🏡',
    gradient: 'linear-gradient(135deg,#1a2c1a,#0D2B1A)',
    images: ['🏡','🌿','🏊','🚗'],
    features: ['حديقة خاصة','مسبح','غرفة ضيوف','مولد كهرباء','كاميرات أمان','خزان مياه'],
    description: 'فيلا عائلية فاخرة في حي رفيديا الراقي بنابلس. مبنية على مساحة 350م² بتصميم معماري حديث مع حديقة ومسبح خاصَين.',
    agentId: 2,
    views: 87, favorites: 12,
    lat: 32.2211, lng: 35.2544,
    verified: true, featured: true,
  },
  {
    id: 3, slug: 'apt-rent-bethlehem',
    title: 'شقة للإيجار — بيت لحم',
    titleEn: 'Apartment for Rent — Bethlehem',
    location: 'بيت لحم، وسط المدينة',
    city: 'بيت لحم', neighborhood: 'وسط المدينة',
    price: 2500, type: 'rent',
    category: 'apt', tag: 'إيجار',
    rooms: 3, baths: 2, area: 130, floor: 2, year: 2018, parking: 1,
    emoji: '🏢',
    gradient: 'linear-gradient(135deg,#2c1a1a,#2B0D0D)',
    images: ['🏢','🛋️','🚿','🏙️'],
    features: ['تكييف','مصعد','إنترنت','قريب من الخدمات','موقف سيارة'],
    description: 'شقة مريحة في قلب بيت لحم، مناسبة للعائلات والأفراد. قريبة من المدارس والمستشفيات ووسائل النقل.',
    agentId: 3,
    views: 412, favorites: 31,
    lat: 31.7054, lng: 35.2024,
    verified: true, featured: false,
  },
  {
    id: 4, slug: 'land-hebron',
    title: 'أرض تجارية — الخليل',
    titleEn: 'Commercial Land — Hebron',
    location: 'الخليل، المنطقة الصناعية',
    city: 'الخليل', neighborhood: 'المنطقة الصناعية',
    price: 400000, type: 'sale',
    category: 'land', tag: 'أرض',
    rooms: 0, baths: 0, area: 600, floor: 0, year: null, parking: 0,
    emoji: '🌿',
    gradient: 'linear-gradient(135deg,#1c2a0a,#152008)',
    images: ['🌿','📐','🗺️','☀️'],
    features: ['تصريح بناء','على شارع رئيسي','كهرباء ومياه','وثائق واضحة'],
    description: 'أرض تجارية مميزة في المنطقة الصناعية بالخليل، مسطحة تماماً، تصاريح بناء متاحة، على شارع رئيسي عرضه 12م.',
    agentId: 3,
    views: 156, favorites: 9,
    lat: 31.5326, lng: 35.0998,
    verified: true, featured: true,
  },
  {
    id: 5, slug: 'apt-jenin-new',
    title: 'شقة عصرية — جنين',
    titleEn: 'Modern Apartment — Jenin',
    location: 'جنين، وسط المدينة',
    city: 'جنين', neighborhood: 'وسط المدينة',
    price: 280000, type: 'sale',
    category: 'apt', tag: 'جديد',
    rooms: 3, baths: 1, area: 110, floor: 4, year: 2024, parking: 1,
    emoji: '🏗️',
    gradient: 'linear-gradient(135deg,#1a1a3c,#0D0D2B)',
    images: ['🏗️','🛋️','🚿','🌅'],
    features: ['تسليم فوري','تشطيب كامل','مصعد','تكييف','ضمان المقاول'],
    description: 'شقة جديدة تسلم فوراً في برج حديث بجنين. تشطيب كامل راقٍ، مصعد كهربائي، موقف خاص في الطابق الأرضي.',
    agentId: 1,
    views: 98, favorites: 14,
    lat: 32.4628, lng: 35.2969,
    verified: false, featured: false,
  },
  {
    id: 6, slug: 'studio-ramallah',
    title: 'استوديو — رام الله',
    titleEn: 'Studio — Ramallah',
    location: 'رام الله، البيرة',
    city: 'رام الله', neighborhood: 'البيرة',
    price: 1800, type: 'rent',
    category: 'apt', tag: 'إيجار',
    rooms: 1, baths: 1, area: 60, floor: 2, year: 2020, parking: 0,
    emoji: '🛋️',
    gradient: 'linear-gradient(135deg,#2a1a2c,#1A0D2B)',
    images: ['🛋️','🍳','🚿','🏙️'],
    features: ['مفروش بالكامل','إنترنت مجاني','كهرباء ومياه مشمولة','قريب من الجامعة'],
    description: 'استوديو مفروش بالكامل في البيرة، مثالي للطلاب والعزاب. الإيجار يشمل الكهرباء والمياه والإنترنت.',
    agentId: 2,
    views: 203, favorites: 27,
    lat: 31.9142, lng: 35.2155,
    verified: true, featured: false,
  },
]

export const AGENTS = [
  {
    id: 1, name: 'أحمد خالد', nameEn: 'Ahmad Khalid',
    role: 'وكيل معتمد', badge: '⭐ ذهبي',
    avatar: 'أخ', rating: 4.9, reviews: 87, deals: 142,
    phone: '+970 59 111 2233', email: 'ahmad@aqar.ps',
    cities: ['رام الله','بيت لحم'], bio: 'خبرة 12 سنة في السوق الفلسطيني.',
  },
  {
    id: 2, name: 'سمر العمر', nameEn: 'Samar Al-Omr',
    role: 'وكيلة معتمدة', badge: '🥈 فضي',
    avatar: 'سع', rating: 4.7, reviews: 54, deals: 98,
    phone: '+970 59 444 5566', email: 'samar@aqar.ps',
    cities: ['نابلس','جنين'], bio: 'متخصصة في العقارات السكنية الفاخرة.',
  },
  {
    id: 3, name: 'كريم ناصر', nameEn: 'Kareem Nasser',
    role: 'وكيل معتمد', badge: '🥇 بلاتيني',
    avatar: 'كن', rating: 5.0, reviews: 112, deals: 201,
    phone: '+970 59 777 8899', email: 'kareem@aqar.ps',
    cities: ['الخليل','بيت لحم'], bio: 'رقم 1 في منطقة الجنوب. خبرة 15 سنة.',
  },
]

export const REVIEWS = [
  { id: 1, name: 'أحمد حسين', initials: 'أح', role: 'اشترى شقة في رام الله', rating: 5, text: 'خدمة ممتازة وسريعة، وجدت شقة أحلامي في رام الله خلال أسبوع فقط. فريق احترافي جداً وودود.' },
  { id: 2, name: 'منى سليمان', initials: 'مس', role: 'أجّرت شقة في نابلس', rating: 5, text: 'الموقع سهل الاستخدام والوكلاء متعاونون جداً. نجحت في تأجير عقاري في أقل من أسبوعين.' },
  { id: 3, name: 'كريم العمر', initials: 'كع', role: 'اشترى فيلا في الخليل', rating: 4, text: 'تجربة رائعة، حاسبة القرض ساعدتني كثيراً في اتخاذ القرار. أنصح الجميع بهذا الموقع.' },
]

export const CITIES = ['رام الله','نابلس','الخليل','بيت لحم','جنين','طولكرم','قلقيلية','أريحا','سلفيت']

export const SERVICES = [
  { icon: '🏠', title: 'بيع العقارات', desc: 'نساعدك في بيع عقارك بأفضل سعر وأسرع وقت ممكن' },
  { icon: '🔑', title: 'إيجار العقارات', desc: 'إيجاد المستأجر المناسب وإدارة العقد بشكل احترافي' },
  { icon: '📊', title: 'التقييم العقاري', desc: 'تقييم دقيق لعقارك بناءً على أسعار السوق الحالية' },
  { icon: '💰', title: 'تمويل عقاري', desc: 'نساعدك في الحصول على أفضل خيارات التمويل البنكي' },
]
